[bans]
multiple-versions = "warn"

deny = [
  { name = "openssl", version = "<0.10.60" },
  { name = "openssl", version = "0.10.63" },
]

skip = []
skip-tree = []

wildcards = "deny"
allow-wildcard-paths = true


[advisories]
yanked = "deny"
unmaintained = "all"
unsound = "all"
ignore = [
    { id = "RUSTSEC-2024-0436", reason = "transitive dependency via rav1e/ image, no direct impact" }
]


[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Zlib",
    "Unicode-DFS-2016",
    "Unicode-3.0",
    "BSL-1.0",
    "OFL-1.1",
    "Ubuntu-font-1.0",
    "NCSA",
    "CC0-1.0",
]

private = { ignore = true }


[sources]
allow-git = []
unknown-git = "deny"
unknown-registry = "deny"
required-git-spec = "rev"

[sources.allow-org]
github = []
